### ISSUE TITLE
importing inputs from .yaml

### ISSUE THREAD

**Issue by FLomb** [RAMP-project/RAMP#1]
It would be nice to allow inputs formulation in a separate .yaml (or similar) file, which is then imported into RAMP and translated into the kind of formulation required by User and Appliances classes.

**Comment by Bachibouzouk** [comment]
Is this now possible? I did not see this being described in the readme.

**Comment by FLomb** [comment]
No, if I remember correctly, we closed this PR after some experimentation because RAMP's input structure is so nested that defining inputs via YAML files would be as messy as the current Python-based definition.
