### ISSUE TITLE
Automatizing the rst updates based on jupyter files

### ISSUE THREAD

**Issue by mohammadamint** [RAMP-project/RAMP#104]
When new changes are implemented on jupyter files for example, the same changes need to be implemented on rst files for the code documentation or the rst files need to be downloaded which seems tedious. 

there should be a workaround this using:

https://nbconvert.readthedocs.io/en/latest/usage.html

**Comment by Bachibouzouk** [comment]
I was thinking the same, to use nbconvert. I use it to run the notebooks to test them :)

**Comment by mohammadamint** [comment]
@Bachibouzouk  What do you think? (Automatizing the conversion of jupyter examples to rst #105)

**Comment by Bachibouzouk** [comment]
This is now merged into `developement`
