### ISSUE TITLE
Add documentation about the user_preference feature

### ISSUE THREAD

**Issue by FLomb** [RAMP-project/RAMP#13]
Several users already asked about this, so there's need for additional documentation.

Below a copy paste from the Gitter chat, which can serve as a minimal bullet list of what needs to be explained:

> - In [this paper](https://ieeexplore.ieee.org/abstract/document/8810571) we needed to model cooking energy demand due to the willingness to simulate a switch to electric cooking appliances. This entailed considering that meal preferences change every day.
> - People don't always eat the same food, right? So, for each main meal (breakfast, lunch, dinner) we modelled multiple "food options", each of which characterised by a different pref_index (1,2,3,...).
> - So, if you look at the file shared by @Stevogallo up in the chat (), for instance, you have lunch_1 (pref_index=1) which is simply one "chicken soup"; whilst lunch_2 is the combination of rice, eggs, platano and meat (4 cooking tasks, all with pref_index =2).
> - Then, each user class has a user_preferences parameter that can go from 0 (default, i.e. not considered) to as much as you want/need; in our case, I guess it was 3, which means that the options for meals among which they can choose every day are up to 3.
> - For every daily profile simulation, each single user (e.g. each family) within the user class will randomise its daily "preference" in terms of what they want to eat. If, on that day, they are randomised to "1", it means that the code will simulate the chicken soup, whilst it will skip all cooking tasks associated to pref_index=2. The day after, maybe, the will instead want a "2" and will eat the combo of those other 4 recipes.
> - This adds a lot more realism, but of course makes sense only when precise information about all main cooking habits/options are available._

**Comment by Stevogallo** [comment]
Version 0.3.1 fixes this.
