### ISSUE TITLE
Missed out on defining a few parameters on the core file

### ISSUE THREAD

**Issue by abhinandan100** [RAMP-project/RAMP#14]
Hello Francesco,  I have observed that the rated power /  capacity  (3rd term  in the appliance sub class) has not been documented in the core file, it can lead to  a struggle for some one having not enough knowledge of python.   
Secondly in the input file all the terms can be explained, the sequencing of instance parameters without a nomenclature may confuse an amateur and the fact that parameters against which no values have been mentioned take the default value from the core file can also be mentioned . 
Also ,  I will suggest on providing some explanation on how to consider the random variabilities in the input or core file , However if it has been explained in the original research article , it can be skipped.

**Comment by FLomb** [comment]
Hi @abhinandan100, could you check if this has been solved by the many upgrades we did in the current development branch?

**Comment by Bachibouzouk** [comment]
@abhinandan100 - the file you might be interested in is https://github.com/RAMP-project/RAMP/blob/development/docs/input_parameters.md

**Comment by abhinandan100** [comment]
Ok thank you,  in this file, all the parameters have been clearly defined, the issue has been resolved
