### ISSUE TITLE
Input file 1 is not getting fed  in the new version

### ISSUE THREAD

**Issue by abhinandan100** [RAMP-project/RAMP#15]
Please check input file 1 is not getting fed in the new version , only input from input file 2 is getting fed into the process, do check that

**Comment by FLomb** [comment]
This comment has been addressed by @Stevogallo on the [Gitter chat](https://gitter.im/RAMP-project). The input file 1 is still read by the latest release, it is just not set as a default. However, I agree that this is currently not explicit enough, and should be made more user friendly. I'll work on that asap

**Comment by FLomb** [comment]
New version 0.3.1 addresses the issue
