### ISSUE TITLE
Probability of Switch on Events distributed among windows, regardless of the size

### ISSUE THREAD

**Issue by Stevogallo** [RAMP-project/RAMP#18]
The probabilty of an appliance being switched on is uniformely distributed between windows, regardless of the size of the windows. This means that if I model two windows, one significantly larger than the other, the appliance will have the same probability of being switched on in both, but this concentrates half of the switch on events in a very limited amount of time, resulting in unjustified peaks.

We propose to change the rationale to a probability of switch on events uniformely distributes along time, and now windows.

The figure refers to:
```
LMI = User("lower middle income",30,0)
User_list.append(LMI)

#Create new appliances

LMI_indoor_bulb = LMI.Appliance(LMI,3,7,2,20,0.2,10)
LMI_indoor_bulb.windows([1170,1440],[0,30],0.35)
```

![Figure_1](https://user-images.githubusercontent.com/33422096/123658582-27a4ac80-d832-11eb-88bc-9a8533970536.png)

**Comment by PasquinoFI** [comment]
Hi, 
I noticed this bug and I think it should be fixed, I'm agree with your proposal but I want to propose a best one.

In my opinion the best solution would be to let the user choose a probability for each windows. It requires the adding of three parameters (one for every windows) but in this way we can replicate a more realistic behavior. 
For examples:
we can switch on a light all the day, but with more probability in the evening's window. At the moment the probability of every windows, as you said, it's the same for every windows. But at the same time, let the probability be calculate from the duration of a windows it could cause other problems.  

Did you catch what I'm saying?

**Comment by Stevogallo** [comment]
Hi @PasquinoFI, yes I see your point, I was thinking the same, but here's my doubt:
The different porbability per each window is not an easy parameter to be used, most users could not be aware of that and prefer not to specify. So it could be a nice idea to implement it (so far if I needed that I used to define two different appliances, one per each window I needed), but it would be important to have a solid "default" case. And in my opinion it would be better to let the probability of switch on events be spread over a total window time instead of single windows.

Maybe implementing your proposal and putting my proposal as default could work, what do you think?

I attach the result of the same user with the modification I'm proposing.
![Figure_1](https://user-images.githubusercontent.com/33422096/123667500-80784300-d83a-11eb-8d69-7c0bf353165b.png)

**Comment by PasquinoFI** [comment]
I think you are right, adding too many parameters could make the creation of an app too complicated and only some apps need to have different probability for each window. So, your proposal is realy good as default case. Different probability parameters could be add as optional.

ps To create more appliances is a good way to solve the problem. We did too. But it makes the program slower.

**Comment by Stevogallo** [comment]
A pull request has been submitted.

**Comment by Stevogallo** [comment]
A pull request has been submitted.
