### ISSUE TITLE
Num_profile is misleading as variable name

### ISSUE THREAD

**Issue by Bachibouzouk** [RAMP-project/RAMP#35]
The variable `num_profile` is used to generate multiple days, however the user could very well want to simulate 100 profiles in order to get a single day profile out of the average of the 100 profiles. What if as a user I want to get a month where each daily profile is the average of 10 simulated profiles, this is not currently possible. I would be in favor of allowing both and being explicit regarding how many days the user want to final timeseries to last and how many profiles are generated to produce each daily profile.

This could be done via another input argument `n_days` for example

**Comment by Bachibouzouk** [comment]
Related to https://github.com/rl-institut/RAMP/issues/11

**Comment by FLomb** [comment]
I agree that the name num_profiles is misleading and I have often faced issues similar to the ones you suggest above. Would you take care of making a PR to address this?

**Comment by Bachibouzouk** [comment]
> Would you take care of making a PR to address this?

Sure :)

**Comment by FLomb** [comment]
To what extent does #52 improve this? To me, it seems like the variable name is still num_profiles, isn't it?

**Comment by Bachibouzouk** [comment]
> To what extent does #52 improve this? To me, it seems like the variable name is still num_profiles, isn't it?

This is why in the message referencing this issue I mentioned it only partly addresses the issue :) . It does so by explicitly providing a way to generate profiles for n days. I will tackle the removal/renaming of `num_profile` in another PR (In general try to make PR as small as possible so they are easier to review/faster to be merged)
