### ISSUE TITLE
Development branch need to be cleaned of superfluous commits

### ISSUE THREAD

**Issue by Bachibouzouk** [RAMP-project/RAMP#41]
There are currently 2 "revert" and "revert of revert" commits on the `development` branch which can be removed. This was done locally in a joint call with @FLomb and need to be force pushed from his local `development` branch using `git checkout development` and then `git push -f`

**Comment by Bachibouzouk** [comment]
Other RAMP developpers/users, please tryout the code in the `development` branch by 
1. running any of your custom ramp input files with it (save the old outputs somewhere else beforehand). Please then write issues for any error thrown by running the code
2. compare the simulation outputs with previous outputs, are there some big differences that you notice?
3.  read the documentation of the `development` branch to see how to convert `.py` input files into `.xlsx` input files, then try the conversion and to run RAMP with the `.xlsx` files and also report bugs


step 1 to 3 describe how one could check more in detail, if you can minimally already only fulfill step 1 it would already make sure it runs without bugs :)

**Comment by FLomb** [comment]
> There are currently 2 "revert" and "revert of revert" commits on the `development` branch which can be removed. This was done locally in a joint call with @FLomb and need to be force pushed from his local `development` branch using `git checkout development` and then `git push -f`

I guess we have sorted this out now, haven't we? Should we close the issue?

**Comment by FLomb** [comment]
Should this issue be closed?
