### ISSUE TITLE
Check requirements for publishing in JOSS

### ISSUE THREAD

**Issue by Bachibouzouk** [RAMP-project/RAMP#43]

**Comment by FLomb** [comment]
JOSS's submission requirements are available from [their docs](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). Essentially, we have all the needed ingredients, except possibly a more thorough testing functionality.

**Comment by Bachibouzouk** [comment]
In the compiled version I see no corresponding author

**Comment by FLomb** [comment]
No? I do see it:
![image](https://github.com/RAMP-project/RAMP/assets/26432077/6cd7b46c-e487-4a59-a4dc-b272299b327d)

**Comment by Bachibouzouk** [comment]
As we are in review process in https://github.com/openjournals/joss-reviews/issues/6418 I will close this issue :)
