### ISSUE TITLE
removing some of the tracked files that are not properly ignored in .gitignore

### ISSUE THREAD

**Issue by mohammadamint** [RAMP-project/RAMP#50]

**Comment by Bachibouzouk** [comment]
@mohammadamint I think it might be good that we work using pull requests rather than pushing directly into the develop branch, what do you think?

**Comment by mohammadamint** [comment]
> @mohammadamint I think it might be good that we work using pull requests rather than pushing directly into the develop branch, what do you think?

Sure. Do you prefer to do it for all the changes? Or only the changes that impact the code itself?

**Comment by Bachibouzouk** [comment]
This issue can be closed right @mohammadamint ?

**Comment by mohammadamint** [comment]
I tracked down most of the files to be ignored. I think we can close the issue.
