### ISSUE TITLE
No autobuild of the doc enabled yet

### ISSUE THREAD

**Issue by Bachibouzouk** [RAMP-project/RAMP#55]
I have just set that up for another repository of mine (I am one of the owner of the repository, for RAMP I can't set it up) and I documented what I did in [this issue](https://github.com/open-plan-tool/documentation/pull/98#issue-1536210374)

**Comment by FLomb** [comment]
I think we can consider this issue closed by #57. Is that right?

**Comment by Bachibouzouk** [comment]
> I think we can consider this issue closed by #57. Is that right?

yes :)
