### ISSUE TITLE
The parameter description are not included in the docs

### ISSUE THREAD

**Issue by Bachibouzouk** [RAMP-project/RAMP#59]
The file `docs/input_parameters.md` doesn't seem to be included in the docs, or was it translated to .rts?

**Comment by mohammadamint** [comment]
Indeed it is not included. I will solve it asap. If you have any changes in the file within the existing PRs, please let me know (so I'll wait for the PRs to be merged). Otherwise, I can immediately solve the issue

**Comment by Bachibouzouk** [comment]
I only added a bullet point within the examples of the doc
