### ISSUE TITLE
Creating RAMP postprocessor

### ISSUE THREAD

**Issue by mohammadamint** [RAMP-project/RAMP#63]
The current version of RAMP is capable of saving the model outcome into a file, and generating some limited, pre-define plots.
In many cases, the user needs to perform further analysis of data, like resampling in terms of time, aggregation of some users or appliances, or statistical analysis. Moreover, the plots are very limited and in many cases, do not cover the needs of the modeller for more advanced analysis.

The idea is to provide RAMP with some specific postprocessing and visualization features to improve the state of the art.
Some features:
1. This can be done by having some postprocessing, and plotting classes that are set as an attribute to the core class (?).
For example:

```
myuser = User(
    user_name = "MyUser",
    num_users = 1,
)

myapp = myuser.add_appliance(
    name = "myapp",
    ...
)

myapp.generate_single_load_profile(peak_time=..., date_start="", date_end="")

# resampling or statistical analysis

myuser.resample(freq='h')
myapp.mean(..)

# saving results in different formats
myuser.to_csv(path)
myapp.to_excel(path)

# visualization
myuser.plot.maximum_power(....)
myapp.plot.average_power(....)

# aggregating data
myuser.aggregate(aggregation = aggregation_dict )
```
2. In addition to RAMP core classes, the post-process classes should be able to read results from files.
for example:
```
from ramp import postprocess

mydata = postprocess.from_file(path="path/to/result/file")
```

**Comment by FLomb** [comment]
As agreed during the last RAMP monthly meeting, this work should happen in a dedicated branch of this repository. In fact, others (like @Bachibouzouk ) have an interest in developing post-processing features, and it would be helpful to have a branch to avoid overlaps.
