### ISSUE TITLE
Automatic docs update seems not to work

### ISSUE THREAD

**Issue by FLomb** [RAMP-project/RAMP#68]
The automated updating of the docs seems not to work properly, at least not today. I did several commits and merged PRs into the main, but the docs were not being compiled, so I had to force-compile them.

Am I missing something or is this a mini bug?

**Comment by Bachibouzouk** [comment]
It is only on for PR into dev, I will make it also for PR into main

**Comment by FLomb** [comment]
What is the stage of this issue? Did we sort it out? If not, what's missing?

**Comment by Bachibouzouk** [comment]
Yes it is done, it is just it was not yet merged into development
