### ISSUE TITLE
Setting up GitHub Actions

### ISSUE THREAD

**Issue by mohammadamint** [RAMP-project/RAMP#71]
To create an automatic workflow for publishing the package into TestPyPi and PyPi, github actions can be used.

publish to pypi
----------------
The action should be set up to the **main** branch and triggered in event of a new **release**

TestPypi
---------
The action can be set up in **dev** branch or a release_canditates branch, and triggered in event a **PR** or **push**

**Comment by FLomb** [comment]
Addressed by PR #72
