### ISSUE TITLE
Issue with the installation

### ISSUE THREAD

**Issue by matteodefelice** [RAMP-project/RAMP#73]
I have tried following the official docs to install this package.
I have created a new anaconda environment using `conda env create -f environment.yml` (please update the documentation, because you use `requirements.yml` that doesn't exist). 
This doesn't install the package. Then I do `python setup.py install` but I get the package `rampdemand` and not `ramp`, the package used in the [quick start](https://rampdemand.readthedocs.io/en/latest/intro.html#quick-start).

**Comment by Bachibouzouk** [comment]
@matteodefelice - thank you for your feedback and sorry to hear that your first experience of ramp is not a pleasant one :( 

We will look into this again, meanwhile if it can be helpful to you, I personally installed a local version for development using `pip install -e .` when being at the root of the repository. I think the fact the pipy package is named `rampdemand` does not prevent you to run `import ramp` then. Have you tried running some of the examples then, do they fail as well?

**Comment by matteodefelice** [comment]
True, I can do `import ramp` but all the examples need the `ramp` package, does it mean that I have to run all the examples from the root folder of the github repo?

**Comment by Bachibouzouk** [comment]
@matteodefelice - normally once you installed the package in your environment you can run ramp from anywhere, provided the environment is active. In a terminal you can type `ramp -h` to see the help of ramp inline. We noticed in the developper discussion that they are two different user types of ramp: people using ramp in python scripts and people using the spreadsheet inputs from the command line. We haven't got the time yet to rework the documentation to make those usage explicit and frictionless regardless which approach the user wants to have.

**Comment by matteodefelice** [comment]
Ok, now I understand. The package title is called `rampdemand` but the package is actually `ramp`, that's a bit confusing.

**Comment by Bachibouzouk** [comment]
It is because `ramp` was already taken on pypi, we are sorry for the confusion it might cause :(

**Comment by FLomb** [comment]
Thanks for spotting these inconsistencies, @matteodefelice. 

@Bachibouzouk I wonder if we should rename `ramp` into `rampdemand` everywhere at this point, to avoid confusion.

**Comment by FLomb** [comment]
I have worked a bit on this in the branch `fix-and-enhance-documentation`. 

I have updated the environment.yml file with `pip` and `rampdemand` so that it installs all that is needed. I have also updated the `README.rst` accordingly. However, there is still an issue with `setup.py`. The installation that we suggest via `python setup.py` leads to an error, whilst `pip install -e` is also not working as it does not seem to find a (working?) `setup.py` file. 

@Bachibouzouk could you perhaps have a look? I think you are the one who set up the `setup.py` file initially.

**Comment by Bachibouzouk** [comment]
You mean `python setup.py install` and `pip install -e  .` commands? Both of them work for me. Did you forget `install` and `.` for the respective commands ?

**Comment by FLomb** [comment]
I consider this issue to be solved by the changes in PR #76, so I am closing it
