### ISSUE TITLE
Empty peak time range error

### ISSUE THREAD

**Issue by JW-Kraft** [RAMP-project/RAMP#80]
I just discovered this issue testing a model with a single appliance for one day.

In the function `calc_peak_time_range` the variable `rand_peak_enlarge` is calculated as follows:
`rand_peak_enlarge = round(math.fabs(peak_time - random.gauss(mu=peak_time, sigma=peak_enlarge * peak_time)))`
Therefore, it can end up being 0 in case `peak_time` and the result of `random.gauss(mu=peak_time, sigma=peak_enlarge * peak_time)` are close enough that their difference rounds to 0.

The function then returns an empty array as peak time range (`np.arange(peak_time - rand_peak_enlarge, peak_time + rand_peak_enlarge)`) which produces an error later on.

For longer timeframes this is just very unlikely to happen.

A simple fix would be to limit `rand_peak_enlarge` to be at least 1:

`rand_peak_enlarge = max(round(math.fabs(peak_time - random.gauss(mu=peak_time, sigma=peak_enlarge * peak_time))), 1)`

**Comment by FLomb** [comment]
Hi, thanks for spotting this issue. I think that the proposed solution makes sense
